# Generated by Django 3.2.11 on 2022-01-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxWeight', models.CharField(max_length=20)),
                ('minWeight', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'weight',
            },
        ),
    ]
